// Hand-drawn pixel sprites. '.' is transparent; every other character is
// looked up in the palette that sits next to the sprite.

export const ship = {
  rows: [
    '.............mkkkk..............',
    '.............mkxkk..............',
    '.............mkkk...............',
    '.............m..................',
    '........wwwwwmwwwww.............',
    '.......wwwwwwmwwwwww.....m......',
    '.......wwwwwwmwwwwww.....m......',
    '.......rrrrrrmrrrrrr...wwmwww...',
    '.......wwwwwwmwwwwww..wwwmwwww..',
    '.......swwwwwmwwwwws..rrrmrrrr..',
    '........sswwwmwwwss...swwmwwws..',
    '.............m.........ssmss....',
    '........wwwwwmwwwww......m......',
    '.......wwwwwwmwwwwww.....m.....m',
    '.......wwwwwwmwwwwww.....m....m.',
    '.......swwwwwmwwwwws.....m...m..',
    '........sswwwmwwwss......m..m...',
    '..l..........m...........m.m....',
    'bbbbbbb......m...........mm.....',
    'bHHHHHbHHHHHHHHHHHHHHHHHHHHHHb..',
    '.bHyyyyyyyyyyyyyyyyyyyyyyyyyHb..',
    '.bBBBoBBBBoBBBBoBBBBoBBBBoBBBb..',
    '..bBBBBBBBBBBBBBBBBBBBBBBBBBb...',
    '...bbbbbbbbbbbbbbbbbbbbbbbbbb...',
    '.....bbbbbbbbbbbbbbbbbbbbbb.....',
  ],
  palette: {
    k: '#0b0f1a',
    x: '#f1f5f9',
    m: '#5a3a1e',
    w: '#f3e9d2',
    s: '#cbb991',
    r: '#b91c1c',
    b: '#3d2210',
    B: '#6b3f1d',
    H: '#8a5528',
    y: '#fbbf24',
    o: '#fde68a',
    l: '#fde047',
  },
};

export const lighthouse = {
  rows: [
    '...r...',
    '..rrr..',
    '.rrrrR.',
    '.dyyyd.',
    '.dyyyd.',
    'ddddddd',
    '.wwwwW.',
    '.wwwwW.',
    '.rrrrR.',
    '.rrrrR.',
    '.wwwwW.',
    '.wwwwW.',
    'rrrrrrR',
    'rrrrrrR',
    'wwwwwwW',
    'wwwddwW',
    'rrrddrR',
    'rrrddrR',
  ],
  palette: {
    r: '#dc2626',
    R: '#991b1b',
    w: '#e2e8f0',
    W: '#94a3b8',
    d: '#0f172a',
    y: '#fde047',
  },
};

export const house = {
  rows: ['..rrrr..', '.rrrrrr.', 'rrrrrrrr', '.hhhhhh.', '.hohhoh.', '.hhhhhh.'],
  palette: { r: '#0c1a33', h: '#132746', o: '#fcd34d' },
};

export const gull = {
  up: ['#.....#', '.#...#.', '..#.#..', '...#...'],
  down: ['.......', '.......', '.##.##.', '#..#..#'],
};

export const bigAnchor = {
  rows: [
    '......oooo......',
    '.....oo..oo.....',
    '.....oo..oo.....',
    '......oooo......',
    '.......oo.......',
    '...oooooooooo...',
    '...oooooooooo...',
    '.......oo.......',
    '.......oo.......',
    '.......oo.......',
    'o......oo......o',
    'oo.....oo.....oo',
    'ooo....oo....ooo',
    '.oo....oo....oo.',
    '.ooo...oo...ooo.',
    '..oooo.oo.oooo..',
    '....oooooooo....',
    '......oooo......',
  ],
};

// 8x8 stat icons (single colour, '#' = lit).
export const icons8 = {
  star: ['...##...', '...##...', '########', '.######.', '..####..', '.######.', '.##..##.', '##....##'],
  commit: ['........', '...##...', '..####..', '########', '########', '..####..', '...##...', '........'],
  pr: ['.....#..', '.......#', '########', '.....#..', '..#.....', '#.......', '########', '..#.....'],
  issue: ['..####..', '.#....#.', '#..##..#', '#..##..#', '#......#', '#..##..#', '.#....#.', '..####..'],
  crate: ['########', '#.#..#.#', '#..##..#', '#.####.#', '#.####.#', '#..##..#', '#.#..#.#', '########'],
  fork: ['##....##', '##....##', '.#....#.', '..#..#..', '...##...', '...##...', '...##...', '...##...'],
  anchor: ['...##...', '..#..#..', '...##...', '.######.', '...##...', '#..##..#', '##.##.##', '.######.'],
};

// 12x12 project icons.
export const projectIcons = {
  anchor: {
    rows: [
      '.....gg.....',
      '....g..g....',
      '.....gg.....',
      '.....gg.....',
      '..gggggggg..',
      '.....gg.....',
      '.....gg.....',
      'g....gg....g',
      'gg...gg...gg',
      '.gg..gg..gg.',
      '..gggggggg..',
      '....gggg....',
    ],
    palette: { g: '#fbbf24' },
  },
  robot: {
    rows: [
      '.....cc.....',
      '.....cc.....',
      '..cccccccc..',
      '.c........c.',
      '.c.ww..ww.c.',
      '.c.ww..ww.c.',
      '.c........c.',
      '.c..cccc..c.',
      '.c........c.',
      '..cccccccc..',
      '...c....c...',
      '..cc....cc..',
    ],
    palette: { c: '#5eead4', w: '#e6f1ff' },
  },
  terminal: {
    rows: [
      'cccccccccccc',
      'crryygcccccc',
      'cccccccccccc',
      'c..........c',
      'c.g........c',
      'c..g.......c',
      'c...g......c',
      'c..g.......c',
      'c.g..wwww..c',
      'c..........c',
      'cccccccccccc',
      '............',
    ],
    palette: { c: '#67e8f9', r: '#fb7185', y: '#fbbf24', g: '#34d399', w: '#e6f1ff' },
  },
  scroll: {
    rows: [
      '.bbbbbbbbbb.',
      'bppppppppppb',
      '.bbbbbbbbbb.',
      '..pppppppp..',
      '..pllllllp..',
      '..pppppppp..',
      '..pllllplp..',
      '..pppppppp..',
      '..plllllpp..',
      '.bbbbbbbbbb.',
      'bppppppppppb',
      '.bbbbbbbbbb.',
    ],
    palette: { b: '#b45309', p: '#fde68a', l: '#92400e' },
  },
  palette: {
    rows: [
      '............',
      '.aaa.bbb.ccc',
      '.aaa.bbb.ccc',
      '.aaa.bbb.ccc',
      '............',
      '.ddd.eee.fff',
      '.ddd.eee.fff',
      '.ddd.eee.fff',
      '............',
      '.ggg.hhh.iii',
      '.ggg.hhh.iii',
      '.ggg.hhh.iii',
    ],
    palette: {
      a: '#fde68a', b: '#fbbf24', c: '#d97706',
      d: '#fda4af', e: '#fb7185', f: '#be123c',
      g: '#a5f3fc', h: '#22d3ee', i: '#0e7490',
    },
  },
  planet: {
    rows: [
      '....bbbb....',
      '..bbggbbbb..',
      '.bbgggbbgbb.',
      '.bggbbbbggb.',
      'rrrrbbbgggbb',
      'bbgrrrrrrbbb',
      'bbbgggbbrrrr',
      '.bbbggbbbbb.',
      '.bbbbbbggbb.',
      '..bbbbbbbb..',
      '....bbbb....',
      '............',
    ],
    palette: { b: '#38bdf8', g: '#34d399', r: '#fde68a' },
  },
};
